---
- name: Set docker image with registry
  set_fact:
    nginx_image: "{{ docker_registry }}/{{ nginx_image }}"
  when:
    - docker_registry is defined
    - docker_registry != 0

- name: Pull nginx image
  docker_image:
    name: "{{ nginx_image }}"
    timeout: "{{ docker_container_timeout }}"
    source: pull
  when:
    - not docker_registry_validate_certs|bool

- name: Pull nginx image with local CA
  docker_image:
    name: "{{ nginx_image }}"
    timeout: "{{ docker_container_timeout }}"
    source: pull
    ca_cert: "{{ ssl_data_host_path }}/{{ docker_registry_ca_cert_file }}"
    validate_certs: true
  when:
    - docker_registry_validate_certs|bool
    - docker_registry_ca_cert_file is defined
    - docker_registry_username is not defined
    - docker_registry_password is not defined

- name: Pull nginx image without local CA
  docker_image:
    name: "{{ nginx_image }}"
    timeout: "{{ docker_container_timeout }}"
    source: pull
    validate_certs: true
  when:
    - docker_registry_validate_certs|bool
    - docker_registry_ca_cert_file is not defined
    - docker_registry_username is not defined
    - docker_registry_password is not defined

- name: Create and start a 'nginx' container
  docker_container:
    name: graylog_web_1
    image: "{{ nginx_image }}"
    state: started
    purge_networks: true
    recreate: true
    restart_policy: always
    security_opts:
      - no-new-privileges
    ports:
      - 80:80
      - 443:443
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /run
    read_only: true
    volumes:
      - "{{ graylog_volume }}/nginx/conf.d/graylog.conf:/etc/nginx/conf.d/graylog.conf:ro,z"
      - "{{ graylog_volume }}/nginx/ssl/:/etc/nginx/ssl/:ro,z"
    networks:
      - name: logging
        links:
          - graylog
        aliases:
          - web

- name: Wait for container will be started
  command: docker inspect --format={{ '{{.State.Status}}' }} graylog_web_1  # noqa 206
  register: result
  until: result.stdout == 'running'
  retries: 5
  delay: 2