---
########################################################################################################################
#                                                  Docker settings
########################################################################################################################

mongo_image: "mongo:5.0.30"

mongo_upgrade: false
