---
- include_tasks: system_info.yaml
  tags: [information]

- include_tasks: file_descriptors.yaml
  tags: [descriptors]

- include_tasks: create_user_group.yaml
  tags: [common]
  when:
    - ((node_exporter_install|bool)
      or (mongodb_exporter_install|bool)
      or (elasticsearch_exporter_install|bool)
      or (proxy_exporter_install|bool))

- include_tasks: certificates_custom.yaml
  tags: [certs]

- include_tasks: certificates_registries.yaml
  tags: [certs]
  when:
    - ((raw_artifacts_registry_validate_certs|bool)
      or (docker_registry_validate_certs|bool))