---
########################################################################################################################
#                                                  Docker settings
########################################################################################################################

opensearch_image: "opensearchproject/opensearch:1.3.20"

########################################################################################################################
#                                               Services settings
########################################################################################################################

## ElasticSearch admin credentials
# default: username=admin and password=admin
opensearch_admin_username: admin
opensearch_admin_password: admin

## OpenSearch user and group who SHOULD has access rights to configure and data directories.
# default: uid=1000 and gid=1000
opensearch_uid: 1000
opensearch_gid: 1000

opensearch_log_level: WARN

migrate_to_opensearch: false

path_repo: archives

# TODO: add s3_repository_plugin
